<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-13T14:47:28 BDT" name="Default suite" finished-at="2023-12-13T14:49:30 BDT" duration-ms="121651">
    <groups>
    </groups>
    <test started-at="2023-12-13T14:47:28 BDT" name="Default test" finished-at="2023-12-13T14:49:30 BDT" duration-ms="121651">
      <class name="automi.shudokkho.Elearning">
        <test-method is-config="true" signature="configAppium()[pri:0, instance:automi.shudokkho.Elearning@70ed52de]" started-at="2023-12-13T14:47:28 BDT" name="configAppium" finished-at="2023-12-13T14:47:55 BDT" duration-ms="27022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAppium -->
        <test-method signature="finishCourse()[pri:0, instance:automi.shudokkho.Elearning@70ed52de]" started-at="2023-12-13T14:47:55 BDT" name="finishCourse" finished-at="2023-12-13T14:49:28 BDT" duration-ms="92309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishCourse -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automi.shudokkho.Elearning@70ed52de]" started-at="2023-12-13T14:49:28 BDT" name="tearDown" finished-at="2023-12-13T14:49:30 BDT" duration-ms="2207" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at automi.shudokkho.Shbase.tearDown(Shbase.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automi.shudokkho.Elearning -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
